import { FREQUENCY_OPTIONS } from "./types";

export const INITAL_ORDER = 1;

const HOUR_IN_MILISECONDS = 60 * 60 * 1000;
const DAY_IN_MILISECONDS = 24 * HOUR_IN_MILISECONDS;

export const frequencySeconds = {
  [FREQUENCY_OPTIONS.hour]: HOUR_IN_MILISECONDS,
  [FREQUENCY_OPTIONS.day]: DAY_IN_MILISECONDS,
  [FREQUENCY_OPTIONS.week]: 7 * DAY_IN_MILISECONDS,
  [FREQUENCY_OPTIONS.month]: 30 * DAY_IN_MILISECONDS,
};
